### ISSUE TITLE
Logo in README

### ISSUE THREAD

**Issue by qbaddev** [Srthmnt/MagicMod#5]
**Logo in README broken.** 

`# ![MagicMod logo](http://shtdev.000webhostapp.com/MM.png)`

Site not found. (Author removed this site)

Fix It!

**Comment by Srthmnt** [comment]
ohh shit

**Comment by Srthmnt** [comment]
my 000webhost account has been deleted :/

**Comment by Srthmnt** [comment]
but i'm making backups

**Comment by qbaddev** [comment]
Add logo to files in project.

**Comment by Srthmnt** [comment]
Fixed
